apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-all
  namespace: ingress-nginx
spec:
  ingress:
  - {}
  egress:
  - {}
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress